name: Swift

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: fwal/setup-swift@v1
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 14
    - name: Get swift version
      run: swift --version
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
