name: Swift

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-11.0
    
    steps:
    - uses: actions/checkout@v2
    - uses: fwal/setup-swift@v1
      with:
        swift-version: "5.3"
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    - name: Setup Xcode 12
      run: sudo xcode-select -s /Applications/Xcode_12.app/Contents/Developer
    - name: Get swift version
      run: swift --version
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
