name: Swift

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    
    - uses: fwal/setup-swift@v1
      with:
        swift-version: "5.3"
    - name: Get swift version
      run: swift --version
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
